# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qs4jNEtyhNAZzoIgKfzZqBhuGVIFkO_l
"""

# Step 1: Import Libraries
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 2: Load Dataset
data = fetch_openml("credit-g", version=1, as_frame=True)
df = data.frame

# Step 3: Identify target column
print("Available columns:", df.columns)
target_column = 'class' if 'class' in df.columns else data.target_names[0]

# Step 4: Encode target column
df[target_column] = df[target_column].apply(lambda x: 1 if x == 'good' else 0)

# Step 5: Convert categorical to numerical
df_encoded = pd.get_dummies(df.drop(target_column, axis=1))

# Step 6: Prepare features and labels
X = df_encoded
y = df[target_column]

# Step 7: Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 8: Train the Model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 9: Predict and Evaluate
y_pred = model.predict(X_test)
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))